db.getCollection('metrics').aggregate([
    {$match: {recent_owner_merged_ratio : {$exists : false}}},
    {$count: "count"}
])

db.getCollection('changes').aggregate([
    //{$match : {status: {$in: ['MERGED', 'ABANDONED']}}},
    {$match : {status: {$in: ['ABANDONED']}}},
    {$match : {"labels.Code-Review.all.value" : {$in : [-2]}}},
    //{$count: 'count'}
])

db.getCollection('changes').aggregate([
    //{$match : {status: {$in: ['MERGED', 'ABANDONED']}}},
    //{$match : {status: {$in: ['ABANDONED']}}},
    {$match : {"messages.author.username" : 'pootlebot'}},
    //{$group}
    //{$count: 'count'}
    {
        $group: {
            _id: 1,
            count: { $sum: 1 },
            time_avg: {$avg: "$meta_date_updated_date_created_diff"},
            time_max: {$max: "$meta_date_updated_date_created_diff"},
            time_min: {$min: "$meta_date_updated_date_created_diff"},
            time_std: {$stdDevPop: "$meta_date_updated_date_created_diff"},
        }
    }
])

db.getCollection('accounts').find({name: 'Pootle bot'})

db.getCollection('changes').find({_number: 25375})

db.getCollection('changes').aggregate([
    //{$match : {status: {$in: ['MERGED', 'ABANDONED']}}},
    {$match : {status: {$in: ['ABANDONED']}}},
    {$match : {"labels.Code-Review.all.value" : {$nin : [-2]}}},
    {$count: 'count'}
])

db.getCollection('changes').aggregate([
    //{$match : {status: {$in: ['MERGED', 'ABANDONED']}}},
    //{$match : {status: {$in: ['ABANDONED']}}},
    {$match : {"messages.author.username" : 'zuul'}},
    //{$group}
    //{$count: 'count'}
    {
        $group: {
            _id: 1,
            count: { $sum: 1 },
            time_avg: {$avg: "$meta_date_updated_date_created_diff"},
            time_max: {$max: "$meta_date_updated_date_created_diff"},
            time_min: {$min: "$meta_date_updated_date_created_diff"},
            time_std: {$stdDevPop: "$meta_date_updated_date_created_diff"},
        }
    }
])

db.getCollection('changes').aggregate([
    //{$match : {status: {$in: ['MERGED', 'ABANDONED']}}},
    //{$match : {status: {$in: ['ABANDONED']}}},
    {$match : {
            "messages.tag" : 'autogenerated:gerrit:abandon',
            meta_date_updated_date_created_diff: {$lte: 1},
        }
    },


    //{$group}
    {$count: 'count'}
    /*{
            $group: {
                _id: 1,
                count: { $sum: 1 },
                time_avg: {$avg: "$meta_date_updated_date_created_diff"},
                time_max: {$max: "$meta_date_updated_date_created_diff"},
                time_min: {$min: "$meta_date_updated_date_created_diff"},
                time_std: {$stdDevPop: "$meta_date_updated_date_created_diff"},
            }
        }*/

])

db.getCollection('changes').aggregate([
    {$match: {
            //status:{$in: ['MERGED', 'ABANDONED']},
            status:'ABANDONED',
            meta_date_updated_date_created_diff: {$lte: 1},
            //meta_date_updated_date_created_diff: {$gte: 1000},
            //"labels.Code-Review.all.value" : {$nin : [2]}
            //meta_date_updated_date_created_diff: {$gte: 60484}
        }
    },
    {$project: {id:1, created:1, status:1, 'messages.date': 1, 'messages.message' : 1}}
    //{$count: 'count'}
])

db.getCollection('changes').aggregate([
    {
        $match: {
            status:{$nin: ['MERGED', 'ABANDONED']},
        }
    },
    {
        $group: {
            _id: "$created",
            count: { $sum: 1 },
        }
    },
    //{$match: {count: {$gte: 2}}},
    //{$count: "count"}
    {$sort: {count : -1}},
    {$limit: 300}
])

db.getCollection('changes').aggregate([
    {$match: {
            //status:{$in: [ 'ABANDONED']},
            created: "2019-07-30 16:02:22.000000000"
        }
    },
    {$project: {id:1, created:1, status:1, 'messages.date': 1, 'messages.message' : 1}}
    //{$count: 'count'}
])